[package]
name = "cdu"
version = "0.1.2"
edition = "2021"
description = "Updates the A record of a domain at Cloudflare with the current outside IP address."

[dependencies]
anyhow = { version = "1.0.80", features = ["backtrace"] }
chrono = { version = "0.4.34", features = ["serde"] }
dns-lookup = "2.0.4"
reqwest = { version = "0.11.24", features = ["blocking", "json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tempfile = "3.10.0"
config = "0.14.0"
clap = { version = "4.5.1", features = ["cargo", "env"] }
log = "0.4.21"
env_logger = "0.11.3"
toml = "0.8.10"
